spring:
  application:
    name: spacrud
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/webcrud_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: webuser
    password: test1234!
  mustache:
    suffix: .html
    enabled: true
    charset: UTF-8


server:
  port: 8087
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mjc813.spacrud
  configuration:
    map-underscore-to-camel-case: true
