spring:
  application:
    name: cinema_crud
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/cinema_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: cinema_user
    password: hiphop1234!
  mustache:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      cache: false
server:
  port: 8087
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mjc813.cinema_crud
  configuration:
    map-underscore-to-camel-case: true