spring:
  application:
    name: food_web
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/food_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    username: food_user
    password: food_9179@
  mustache:
    suffix: .html
    servlet:
      cache: false
  jpa:
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.daum.net  # 발송 메일 서버 주소 (예: Gmail)
    port: 465  # SMTP 포트
    username:   # 보내는 이메일 주소
    password:   # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true  # SMTP 인증 사용 여부
          starttls:
            enable: true  # TLS 사용 여부

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.mjc813.food_web
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8287

