spring:
  application:
    name: band_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/band_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: band_user
    password: band_4321@
  mustache:
    suffix: .html
    servlet:
      cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8373
