spring:
  application:
    name: swimpool_app
  datasource: # mysql ???
    url: jdbc:mysql://localhost:3306/swimpool_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC ???? ??? (MySQL? ??)
    username: swimmer  # ?????? ??? ??
    password: hiphop1234! # ?????? ????

server:
  port: 8084